apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 2ec0e9ba-37bd-43e5-95ac-1bf9a78b4d08
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-ticker
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_ticker_visual_identity
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_ticker_visual_identity
